version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT:-8080}:8080"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
      - MAX_UPLOAD_SIZE=52428800
      - PORT=${PORT:-8080}
    volumes:
      # Mount the data directory for examples
      - ./flask_app/data:/app/flask_app/data
      # Optional: mount for development
      # - ./flask_app:/app/flask_app
      # - ./src:/app/src
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s